#!/bin/sh
dir=$HOME/.screenlayout

set -e
outputs=`xrandr |awk '/^\s/{next} $2=="connected" {print $1}'`

for output in $outputs
do
    # disable DP chained monitors
    if [ "`echo $output|tr -d '0-9'`"  == "DP---" ]
    then
        xrandr --output $output --off
    fi
done

for output in $outputs
do
    xrandr --output $output --auto
done

name="$dir/`xrandr --listmonitors | awk  'BEGIN{FS="[\/ \t]*" } /[0-9]:/{n = n $7 "-" $5} END{print n}'`.sh"



if [ -f "$name" -a -s "$name" ] ; then 
    exec "$name"
else 
    echo new screenlayout "$name"
    touch "$name"
    arandr 
fi

find "$dir" -name '*.sh' -size 0 -type f -delete 
